# -*- mode: Python -*-

# For more on Extensions, see: https://docs.tilt.dev/extensions.html
load('ext://restart_process', 'docker_build_with_restart')

# Records the current time, then kicks off a server update.
# Normally, you would let Tilt do deploys automatically, but this
# shows you how to set up a custom workflow that measures it.
local_resource(
    'deploy',
    'python3 ./record-start-time.py',
    deps=['./record-start-time.py'],
)

local_resource(
    'build',
    'dotnet publish -c Release -o out',
    deps=['hello-tilt'],
    ignore=['hello-tilt/obj'],
    resource_deps=['deploy'],
)

docker_build_with_restart(
    'hello-tilt',
    'out',
    entrypoint=['dotnet', 'hello-tilt.dll'],
    dockerfile='Dockerfile',
    live_update=[
        sync('out', '/app/out'),
    ],
)

k8s_yaml('kubernetes.yaml')
k8s_resource('hello-tilt', port_forwards='8080:8080', resource_deps=['build'])
